language: r
r:
    - oldrel
    - release
    - devel
os:
    - osx
    - linux

matrix:
    exclude:
    - r: devel
      os: osx
    - r: release
      os: osx

repos:
    CRAN: https://cran.r-project.org
